# SPDX-FileCopyrightText: Copyright (C) 2017-2025 Fabr√≠cio Barros Cabral
# SPDX-License-Identifier: MIT
[files]
extend-exclude = [
  ".venv/**",
  "venv/**",
  ".git/**",
  "__pycache__/**",
  "*.pyc",
  "dist/**",
  "build/**",
  "target/**",
  "*.svg",
]

[default.extend-words]
nam = "nam"
